# Generated by Django 4.2 on 2023-04-06 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Región')),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreApellido', models.CharField(max_length=100, verbose_name='Nombre y Apellido')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alias')),
                ('cc', models.IntegerField(verbose_name='N° Cedula')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('enterado', models.IntegerField(choices=[(1, 'web'), (2, 'tv'), (3, 'redes sociales'), (4, 'amigo')])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votar.candidato')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votar.comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votar.region', verbose_name='Region')),
            ],
        ),
    ]
