# Generated by Django 4.2 on 2023-04-06 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votar', '0002_alter_votacion_enterado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Comuna')),
            ],
        ),
        migrations.AlterField(
            model_name='votacion',
            name='enterado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votar.enterado'),
        ),
    ]
