# Generated by Django 4.2 on 2023-04-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votar', '0003_enterado_alter_votacion_enterado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacion',
            name='cc',
            field=models.IntegerField(unique=True, verbose_name='N° Cedula'),
        ),
    ]
